name: PR Comment Trigger

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: read
  actions: write

jobs:
  slash-command-dispatch:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      ) &&
      startsWith(github.event.comment.body, '/check')
    steps:
      - name: Get PR head SHA
        id: get_sha
        run: |
          SHA=$(gh pr view ${{ github.event.issue.number }} --json headRefOid --jq '.headRefOid')
          echo "sha=$SHA" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Smoke Tests
        run: |
          gh workflow run smoke-test.yml --ref "${{ steps.get_sha.outputs.sha }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

      - name: Trigger Playground E2E Tests
        run: |
          gh workflow run playground-e2e-tests.yml --ref "${{ steps.get_sha.outputs.sha }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
